run:
  go: '1.23'

linters:
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - canonicalheader
  - containedctx
  - contextcheck
  - copyloopvar
  - decorder
  - dogsled
  - dupl
  - dupword
  - durationcheck
  - err113
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - fatcontext
  - forbidigo
  - forcetypeassert
  - gci
  - gocheckcompilerdirectives
  - gochecksumtype
  - gocritic
  - godot
  - gofmt
  - gofumpt
  - goheader
  - goimports
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  - gosimple
  - gosmopolitan
  - govet
  - grouper
  - iface
  - importas
  - inamedparam
  - ineffassign
  - interfacebloat
  - intrange
  - ireturn
  - loggercheck
  - makezero
  - mirror
  - misspell
  - musttag
  - nilerr
  - nolintlint
  - nosprintfhostport
  - perfsprint
  - prealloc
  - predeclared
  - promlinter
  - protogetter
  - reassign
  - revive
  - rowserrcheck
  - sloglint
  - spancheck
  - sqlclosecheck
  - staticcheck
  - stylecheck
  - tagalign
  - tenv
  - testableexamples
  - testifylint
  - thelper
  - typecheck
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - wastedassign
  - whitespace
  - zerologlint
  disable:
  - cyclop
  - depguard
  - exhaustive
  - exhaustruct
  - funlen
  - ginkgolinter
  - gochecknoglobals
  - gochecknoinits
  - gocognit
  - goconst
  - gocyclo
  - godox
  - gosec
  - lll
  - maintidx
  - nakedret
  - nestif
  - nilnil
  - nlreturn
  - noctx
  - nonamedreturns
  - paralleltest
  - recvcheck
  - tagliatelle
  - testpackage
  - tparallel
  - varnamelen
  - wrapcheck
  - wsl

linters-settings:
  forbidigo:
    forbid:
    - ^archive/zip\.
    - ^compress/gzip\.
    - ^fmt\.Print.*$
    - ^ioutil\..*$
    - ^os\.(DirEntry|ErrExist|ErrNotExist|FileInfo|FileMode|Is.*|Mode.*)$
  gci:
    sections:
    - standard
    - default
    - prefix(github.com/twpayne/go-mbtiles)
  gocritic:
    enable-all: true
    disabled-checks:
    - emptyFallthrough
    - hugeParam
    - rangeValCopy
    - unnamedResult
    - whyNoLint
  gofumpt:
    extra-rules: true
    module-path: github.com/twpayne/go-mbtiles
  goimports:
    local-prefixes: github.com/twpayne/go-mbtiles
  govet:
    disable:
    - fieldalignment
    - shadow
    enable-all: true
  misspell:
    locale: US
    ignore-words:
    - ackward
  stylecheck:
    checks:
    - all

issues:
  include:
  - EXC0011 # include issues about comments from `stylecheck`
  exclude-rules:
  - linters:
    - err113
    text: do not define dynamic errors, use wrapped static errors instead
  - linters:
    - revive
    text: unused-parameter
