language: go

go:
        - 1.x
        - 1.8.x
        - 1.7.x
        - 1.6.x
        - 1.5.x

script:
        - go test -v ./...
        - go test -cover -race ./...
        - go vet ./...
        - test -z "$(go fmt ./...)"

sudo: false
